/**
 * Resources Data - Complete Resource Library
 *
 * Port of all 62 resources from v2 with proper TypeScript types
 * and actual content paths.
 */

import {
  Resource,
  ResourceCategory,
  ResourceCategoryType,
  ResourceType,
} from '@/types/resources';
import {
  BookOpen,
  Award,
  Target,
  MessageSquare,
  Clock,
  CheckCircle2,
  LayoutTemplate,
  BarChart3,
  Zap,
  TrendingUp,
  Lightbulb,
  Shield,
  Calendar,
  FileCheck,
  Briefcase,
  Users,
  Filter,
} from 'lucide-react';

/**
 * Resource categories with icons and colors
 */
export const categories: ResourceCategory[] = [
  {
    id: 'all',
    name: 'All Resources',
    description: 'Browse the complete library',
    icon: '📚',
    gradient: 'from-gray-500 to-slate-600',
    resourceCount: 62,
  },
  {
    id: 'mindful-leadership',
    name: 'Mindful Leadership',
    description: 'Reflection tools, guided meditations, leadership prompts',
    icon: '🧠',
    gradient: 'from-emerald-500 to-teal-600',
    resourceCount: 13,
  },
  {
    id: 'ai-automation',
    name: 'AI + Automation',
    description: 'Lead magnets, calculators, workflows, tutorials',
    icon: '⚡',
    gradient: 'from-violet-500 to-purple-600',
    resourceCount: 13,
  },
  {
    id: 'personal-growth',
    name: 'Personal Growth',
    description: 'Self-coaching worksheets, anti-fragility guides',
    icon: '🌱',
    gradient: 'from-amber-500 to-orange-600',
    resourceCount: 12,
  },
  {
    id: 'remote-work',
    name: 'Remote Work Resources',
    description: 'Productivity checklists, workspace setup guides',
    icon: '🏠',
    gradient: 'from-blue-500 to-indigo-600',
    resourceCount: 11,
  },
  {
    id: 'overcoming-adversity',
    name: 'Overcoming Adversity',
    description: 'Audio stories, journaling prompts, resilience maps',
    icon: '🎯',
    gradient: 'from-rose-500 to-pink-600',
    resourceCount: 12,
  },
];

/**
 * Icon mapping for categories
 */
export const categoryIcons: Record<string, React.ElementType> = {
  all: Filter,
  leadership: Award,
  'team-management': Users,
  productivity: Zap,
  communication: MessageSquare,
  templates: LayoutTemplate,
  assessments: BarChart3,
  'mindful-leadership': Lightbulb,
  'ai-automation': Target,
  'personal-growth': TrendingUp,
  'remote-work': Briefcase,
  'overcoming-adversity': Shield,
};

/**
 * Type mapping for icon rendering
 */
export const typeIcons: Record<ResourceType, React.ElementType> = {
  PDF: BookOpen,
  Template: LayoutTemplate,
  Guide: Lightbulb,
  Audio: MessageSquare,
  Video: TrendingUp,
  Checklist: CheckCircle2,
  Workbook: FileCheck,
  Assessment: BarChart3,
  Framework: Target,
};

/**
 * Comprehensive resources data - All 62 resources from v2
 */
export const resources: Resource[] = [
  // === MINDFUL LEADERSHIP (13 resources) ===
  {
    id: '2',
    slug: 'mindful-leadership-reflection-journal',
    title: 'Mindful Leadership Reflection Journal',
    description: 'Daily prompts and exercises for conscious leadership',
    category: 'mindful-leadership',
    type: 'Template',
    featured: true,
    downloads: 18900,
    difficulty: 'Beginner',
    timeToRead: '10 min',
    targetAudience: 'All Leaders',
    whatYoullLearn: [
      'Daily reflection practices',
      'Self-awareness techniques',
      'Leadership presence development',
      'Emotional regulation skills',
    ],
    seoTitle: 'Mindful Leadership Reflection Journal - Daily Prompts for Conscious Leaders',
    seoDescription:
      'Transform your leadership with daily reflection prompts. Build self-awareness, emotional intelligence, and authentic presence.',
    keywords: [
      'mindful leadership',
      'reflection journal',
      'conscious leadership',
      'self-awareness',
      'leadership development',
    ],
    contentPath: 'production/week1/resource1-mindful-leadership-journal/summary.md',
  },
  {
    id: '13',
    slug: 'mindful-decision-making-blueprint',
    title: 'Mindful Decision-Making Blueprint',
    description: 'High-stakes decisions with calm and clarity',
    category: 'mindful-leadership',
    type: 'PDF',
    featured: false,
    downloads: 7800,
    difficulty: 'Advanced',
    timeToRead: '30 min',
    targetAudience: 'Executives, Founders',
    whatYoullLearn: [
      'Strategic pause framework',
      'Facts vs. stories separation',
      'Emotional data interpretation',
      'Aligned action planning',
    ],
    contentPath: 'production/week1/resource2-strategic-pause-guide/strategic-pause-guide-page1.md',
  },
  {
    id: '14',
    slug: 'conscious-communication-playbook',
    title: 'Conscious Communication Playbook',
    description: 'Lead difficult conversations with empathy',
    category: 'mindful-leadership',
    type: 'Guide',
    featured: false,
    downloads: 9200,
    difficulty: 'Intermediate',
    timeToRead: '35 min',
    targetAudience: 'All Leaders',
  },
  {
    id: '15',
    slug: 'weekly-leadership-reflection-template',
    title: 'Weekly Leadership Reflection Template',
    description: 'Track wins, blind spots, priorities',
    category: 'mindful-leadership',
    type: 'Template',
    featured: false,
    downloads: 11700,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'All Leaders',
  },
  {
    id: '16',
    slug: 'meeting-presence-checklist',
    title: 'Meeting Presence Checklist',
    description: 'Improve focus and facilitation',
    category: 'mindful-leadership',
    type: 'Checklist',
    featured: false,
    downloads: 8600,
    difficulty: 'Beginner',
    timeToRead: '10 min',
    targetAudience: 'All Leaders',
    contentPath: 'production/week1/resource3-mindful-meeting-checklist/mindful-meeting-checklist.md',
  },
  {
    id: '17',
    slug: 'strategic-pause-audio-practice',
    title: 'Strategic Pause Audio Practice',
    description: 'Reset stress and lead with composure',
    category: 'mindful-leadership',
    type: 'Audio',
    featured: false,
    downloads: 12400,
    difficulty: 'Beginner',
    timeToRead: '10 min',
    targetAudience: 'All Leaders',
  },
  {
    id: '18',
    slug: 'values-aligned-leadership-workbook',
    title: 'Values-Aligned Leadership Workbook',
    description: 'Define values and translate to actions',
    category: 'mindful-leadership',
    type: 'Workbook',
    featured: false,
    downloads: 9800,
    difficulty: 'Intermediate',
    timeToRead: '45 min',
    targetAudience: 'Senior Leaders',
  },
  {
    id: '19',
    slug: 'executive-presence-video-mini-course',
    title: 'Executive Presence Video Mini-Course',
    description: 'Voice, posture, communication presence',
    category: 'mindful-leadership',
    type: 'Video',
    featured: false,
    downloads: 15200,
    difficulty: 'Intermediate',
    timeToRead: '40 min',
    targetAudience: 'Senior Leaders, Executives',
  },
  {
    id: '20',
    slug: 'leadership-one-on-one-agenda-template',
    title: 'Leadership One-on-One Agenda Template',
    description: 'Structure for coaching and trust',
    category: 'mindful-leadership',
    type: 'Template',
    featured: false,
    downloads: 13400,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'Managers, Team Leads',
  },
  {
    id: '21',
    slug: 'mindful-team-rituals-guide',
    title: 'Mindful Team Rituals Guide',
    description: 'Build team rituals for focus and morale',
    category: 'mindful-leadership',
    type: 'Guide',
    featured: false,
    downloads: 8900,
    difficulty: 'Intermediate',
    timeToRead: '25 min',
    targetAudience: 'Team Leaders',
  },
  {
    id: '22',
    slug: 'burnout-prevention-for-leaders-checklist',
    title: 'Burnout Prevention for Leaders Checklist',
    description: 'Protect energy while maintaining impact',
    category: 'mindful-leadership',
    type: 'Checklist',
    featured: false,
    downloads: 16200,
    difficulty: 'Intermediate',
    timeToRead: '20 min',
    targetAudience: 'All Leaders',
    contentPath: 'production/burnout-prevention-checklist.md',
  },
  {
    id: '12',
    slug: 'leadership-presence-workshop-video',
    title: 'Leadership Presence Workshop Video',
    description: 'Building authentic presence and influence',
    category: 'mindful-leadership',
    type: 'Video',
    featured: false,
    downloads: 11000,
    difficulty: 'Intermediate',
    timeToRead: '35 min',
    targetAudience: 'All Leaders',
  },
  {
    id: '7',
    slug: 'team-mindfulness-meditation-pack',
    title: 'Team Mindfulness Meditation Pack',
    description: 'Guided group sessions for team wellness',
    category: 'mindful-leadership',
    type: 'Audio',
    featured: false,
    downloads: 7400,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'Team Leaders',
  },

  // === AI + AUTOMATION (13 resources) ===
  {
    id: '1',
    slug: 'inclusive-automation-readiness-kit',
    title: 'Inclusive Automation Readiness Kit',
    description: 'Self-assessment and checklist for automation readiness',
    category: 'ai-automation',
    type: 'PDF',
    featured: true,
    downloads: 22100,
    difficulty: 'Intermediate',
    timeToRead: '30 min',
    targetAudience: 'Business Leaders, Operations',
    whatYoullLearn: [
      'Assess automation readiness',
      'Identify quick wins',
      'Build inclusive automation',
      'Avoid common pitfalls',
    ],
    contentPath: 'production/week3/resource3-inclusive-automation-readiness-kit/inclusive-automation-readiness-kit-complete.md',
  },
  {
    id: '5',
    slug: 'ai-strategy-templates-small-business',
    title: 'AI Strategy Templates for Small Business',
    description: 'Ready-to-use AI implementation templates',
    category: 'ai-automation',
    type: 'Template',
    featured: false,
    downloads: 14300,
    difficulty: 'Intermediate',
    timeToRead: '25 min',
    targetAudience: 'Small Business Owners',
  },
  {
    id: '11',
    slug: 'ai-email-automation-templates',
    title: 'AI Email Automation Templates',
    description: 'Intelligent email workflow templates',
    category: 'ai-automation',
    type: 'Template',
    featured: false,
    downloads: 18900,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '23',
    slug: 'ai-opportunity-mapping-canvas',
    title: 'AI Opportunity Mapping Canvas',
    description: 'Identify and prioritize AI use cases',
    category: 'ai-automation',
    type: 'Template',
    featured: false,
    downloads: 9800,
    difficulty: 'Intermediate',
    timeToRead: '20 min',
    targetAudience: 'Business Leaders',
  },
  {
    id: '24',
    slug: 'no-code-automation-starter-guide',
    title: 'No-Code Automation Starter Guide',
    description: 'Automate tasks without writing code',
    category: 'ai-automation',
    type: 'Guide',
    featured: false,
    downloads: 15600,
    difficulty: 'Beginner',
    timeToRead: '30 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '25',
    slug: 'ai-prompt-library-for-founders',
    title: 'AI Prompt Library for Founders',
    description: 'High-performing prompts for business',
    category: 'ai-automation',
    type: 'PDF',
    featured: false,
    downloads: 24500,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'Founders, Executives',
  },
  {
    id: '26',
    slug: 'lead-capture-automation-checklist',
    title: 'Lead Capture Automation Checklist',
    description: 'End-to-end lead capture automation',
    category: 'ai-automation',
    type: 'Checklist',
    featured: false,
    downloads: 11200,
    difficulty: 'Intermediate',
    timeToRead: '20 min',
    targetAudience: 'Marketers, Growth Leads',
  },
  {
    id: '27',
    slug: 'automated-content-workflow-template',
    title: 'Automated Content Workflow Template',
    description: 'Plan and schedule content with AI',
    category: 'ai-automation',
    type: 'Template',
    featured: false,
    downloads: 13700,
    difficulty: 'Intermediate',
    timeToRead: '25 min',
    targetAudience: 'Content Creators, Marketers',
  },
  {
    id: '28',
    slug: 'ai-tool-evaluation-framework',
    title: 'AI Tool Evaluation Framework',
    description: 'Select AI tools based on ROI',
    category: 'ai-automation',
    type: 'Guide',
    featured: false,
    downloads: 16800,
    difficulty: 'Advanced',
    timeToRead: '35 min',
    targetAudience: 'Technical Leaders',
    contentPath: 'production/week3/resource5-ai-tools-evaluation-framework/ai-tools-evaluation-framework.md',
  },
  {
    id: '29',
    slug: 'automation-sop-builder-pdf',
    title: 'Automation SOP Builder PDF',
    description: 'Document SOPs for automation',
    category: 'ai-automation',
    type: 'PDF',
    featured: false,
    downloads: 9400,
    difficulty: 'Intermediate',
    timeToRead: '30 min',
    targetAudience: 'Operations Managers',
  },
  {
    id: '30',
    slug: 'ai-systems-weekly-audit-checklist',
    title: 'AI Systems Weekly Audit Checklist',
    description: 'Keep AI workflows accurate and safe',
    category: 'ai-automation',
    type: 'Checklist',
    featured: false,
    downloads: 10300,
    difficulty: 'Intermediate',
    timeToRead: '15 min',
    targetAudience: 'AI Implementers',
  },
  {
    id: '31',
    slug: 'voice-ai-assistant-setup-audio',
    title: 'Voice AI Assistant Setup Audio',
    description: 'Configure voice assistant for support',
    category: 'ai-automation',
    type: 'Audio',
    featured: false,
    downloads: 7100,
    difficulty: 'Beginner',
    timeToRead: '10 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '32',
    slug: 'automation-stack-architecture-video',
    title: 'Automation Stack Architecture Video',
    description: 'Connect apps into automation stack',
    category: 'ai-automation',
    type: 'Video',
    featured: false,
    downloads: 12900,
    difficulty: 'Advanced',
    timeToRead: '40 min',
    targetAudience: 'Technical Leaders',
  },

  // === PERSONAL GROWTH (12 resources) ===
  {
    id: '4',
    slug: 'anti-fragility-workbook',
    title: 'Anti-Fragility Workbook',
    description: 'Build resilience and thrive through challenges',
    category: 'personal-growth',
    type: 'PDF',
    featured: true,
    downloads: 19800,
    difficulty: 'Intermediate',
    timeToRead: '45 min',
    targetAudience: 'All Professionals',
    whatYoullLearn: [
      'Build anti-fragile mindset',
      'Transform stress into growth',
      'Develop resilience practices',
      'Thrive through uncertainty',
    ],
    contentPath: 'production/anti-fragility-workbook.md',
  },
  {
    id: '9',
    slug: 'goal-setting-framework-canvas',
    title: 'Goal Setting Framework Canvas',
    description: 'Visual framework for meaningful goals',
    category: 'personal-growth',
    type: 'Template',
    featured: false,
    downloads: 14200,
    difficulty: 'Beginner',
    timeToRead: '20 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '33',
    slug: 'personal-vision-clarity-workbook',
    title: 'Personal Vision Clarity Workbook',
    description: 'Clarify values and goals',
    category: 'personal-growth',
    type: 'Workbook',
    featured: false,
    downloads: 11600,
    difficulty: 'Intermediate',
    timeToRead: '40 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '34',
    slug: 'growth-mindset-reframe-guide',
    title: 'Growth Mindset Reframe Guide',
    description: 'Reframe setbacks into experiments',
    category: 'personal-growth',
    type: 'Guide',
    featured: false,
    downloads: 13400,
    difficulty: 'Beginner',
    timeToRead: '25 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '35',
    slug: '90-day-habit-tracker-template',
    title: '90-Day Habit Tracker Template',
    description: 'Track and sustain habits',
    category: 'personal-growth',
    type: 'Template',
    featured: false,
    downloads: 17800,
    difficulty: 'Beginner',
    timeToRead: '10 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '36',
    slug: 'self-reflection-sunday-checklist',
    title: 'Self-Reflection Sunday Checklist',
    description: 'Review progress and reset priorities',
    category: 'personal-growth',
    type: 'Checklist',
    featured: false,
    downloads: 12100,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '37',
    slug: 'confidence-building-through-action-template',
    title: 'Confidence Building Template',
    description: 'Turn fear into action steps',
    category: 'personal-growth',
    type: 'Template',
    featured: false,
    downloads: 15300,
    difficulty: 'Intermediate',
    timeToRead: '25 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '38',
    slug: 'identity-upgrade-field-guide',
    title: 'Identity Upgrade Field Guide',
    description: 'Shift limiting identity stories',
    category: 'personal-growth',
    type: 'Guide',
    featured: false,
    downloads: 9700,
    difficulty: 'Advanced',
    timeToRead: '35 min',
    targetAudience: 'Senior Professionals',
  },
  {
    id: '39',
    slug: 'emotional-resilience-journal',
    title: 'Emotional Resilience Journal',
    description: 'Journal for emotional regulation',
    category: 'personal-growth',
    type: 'PDF',
    featured: false,
    downloads: 18800,
    difficulty: 'Intermediate',
    timeToRead: '20 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '40',
    slug: 'monthly-reset-checklist',
    title: 'Monthly Reset Checklist',
    description: 'Declutter and realign priorities',
    category: 'personal-growth',
    type: 'Checklist',
    featured: false,
    downloads: 14500,
    difficulty: 'Beginner',
    timeToRead: '20 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '41',
    slug: 'morning-momentum-audio-practice',
    title: 'Morning Momentum Audio Practice',
    description: 'Start day with purpose and calm',
    category: 'personal-growth',
    type: 'Audio',
    featured: false,
    downloads: 16700,
    difficulty: 'Beginner',
    timeToRead: '10 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '42',
    slug: 'personal-reinvention-video-series',
    title: 'Personal Reinvention Video Series',
    description: 'Navigate career and life pivots',
    category: 'personal-growth',
    type: 'Video',
    featured: false,
    downloads: 13900,
    difficulty: 'Intermediate',
    timeToRead: '50 min',
    targetAudience: 'All Professionals',
  },

  // === REMOTE WORK (11 resources) ===
  {
    id: '3',
    slug: 'remote-work-productivity-masterclass',
    title: 'Remote Work Productivity Masterclass',
    description: 'Transform your home office into productivity powerhouse',
    category: 'remote-work',
    type: 'Guide',
    featured: true,
    downloads: 21400,
    difficulty: 'Intermediate',
    timeToRead: '40 min',
    targetAudience: 'Remote Workers',
    whatYoullLearn: [
      'Home office optimization',
      'Deep work strategies',
      'Async communication',
      'Work-life balance',
    ],
  },
  {
    id: '8',
    slug: 'digital-nomad-workspace-setup-guide',
    title: 'Digital Nomad Workspace Setup Guide',
    description: 'Create perfect portable office',
    category: 'remote-work',
    type: 'Guide',
    featured: false,
    downloads: 11200,
    difficulty: 'Beginner',
    timeToRead: '25 min',
    targetAudience: 'Digital Nomads',
  },
  {
    id: '43',
    slug: 'remote-work-focus-planner',
    title: 'Remote Work Focus Planner',
    description: 'Structure deep work blocks',
    category: 'remote-work',
    type: 'PDF',
    featured: false,
    downloads: 15800,
    difficulty: 'Intermediate',
    timeToRead: '20 min',
    targetAudience: 'Remote Workers',
  },
  {
    id: '44',
    slug: 'async-communication-guide-for-teams',
    title: 'Async Communication Guide for Teams',
    description: 'Improve async collaboration',
    category: 'remote-work',
    type: 'Guide',
    featured: false,
    downloads: 18600,
    difficulty: 'Intermediate',
    timeToRead: '30 min',
    targetAudience: 'Remote Teams',
  },
  {
    id: '45',
    slug: 'remote-onboarding-checklist',
    title: 'Remote Onboarding Checklist',
    description: 'Onboard remote hires smoothly',
    category: 'remote-work',
    type: 'Checklist',
    featured: false,
    downloads: 19300,
    difficulty: 'Beginner',
    timeToRead: '20 min',
    targetAudience: 'HR, Managers',
  },
  {
    id: '46',
    slug: 'weekly-sprint-planning-template',
    title: 'Weekly Sprint Planning Template',
    description: 'Remote-friendly sprint planning',
    category: 'remote-work',
    type: 'Template',
    featured: false,
    downloads: 12400,
    difficulty: 'Intermediate',
    timeToRead: '25 min',
    targetAudience: 'Team Leads',
  },
  {
    id: '47',
    slug: 'distributed-team-productivity-playbook',
    title: 'Distributed Team Productivity Playbook',
    description: 'Manage teams across time zones',
    category: 'remote-work',
    type: 'Guide',
    featured: false,
    downloads: 17100,
    difficulty: 'Advanced',
    timeToRead: '45 min',
    targetAudience: 'Team Leaders',
  },
  {
    id: '48',
    slug: 'home-office-ergonomics-pdf',
    title: 'Home Office Ergonomics PDF',
    description: 'Ergonomic setup guide',
    category: 'remote-work',
    type: 'PDF',
    featured: false,
    downloads: 13800,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'Remote Workers',
  },
  {
    id: '49',
    slug: 'remote-team-rituals-template',
    title: 'Remote Team Rituals Template',
    description: 'Standups and retros library',
    category: 'remote-work',
    type: 'Template',
    featured: false,
    downloads: 14900,
    difficulty: 'Intermediate',
    timeToRead: '30 min',
    targetAudience: 'Team Leaders',
  },
  {
    id: '50',
    slug: 'deep-work-environment-checklist',
    title: 'Deep Work Environment Checklist',
    description: 'Optimize space for focus',
    category: 'remote-work',
    type: 'Checklist',
    featured: false,
    downloads: 16500,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'All Remote Workers',
  },
  {
    id: '52',
    slug: 'virtual-collaboration-tools-video-guide',
    title: 'Virtual Collaboration Tools Video',
    description: 'Configure collaboration stack',
    category: 'remote-work',
    type: 'Video',
    featured: false,
    downloads: 10400,
    difficulty: 'Intermediate',
    timeToRead: '35 min',
    targetAudience: 'Remote Teams',
  },

  // === OVERCOMING ADVERSITY (12 resources) ===
  {
    id: '6',
    slug: 'resilience-audio-series',
    title: 'Resilience Audio Series',
    description: 'Inspiring stories and guided meditations',
    category: 'overcoming-adversity',
    type: 'Audio',
    featured: true,
    downloads: 23700,
    difficulty: 'Beginner',
    timeToRead: '30 min',
    targetAudience: 'All Professionals',
    whatYoullLearn: [
      'Build emotional resilience',
      'Navigate setbacks',
      'Find strength in adversity',
      'Recover and grow',
    ],
  },
  {
    id: '10',
    slug: 'overcoming-burnout-recovery-plan',
    title: 'Overcoming Burnout Recovery Plan',
    description: 'Step-by-step burnout recovery roadmap',
    category: 'overcoming-adversity',
    type: 'Checklist',
    featured: false,
    downloads: 28400,
    difficulty: 'Intermediate',
    timeToRead: '25 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '53',
    slug: 'resilience-under-pressure-workbook',
    title: 'Resilience Under Pressure Workbook',
    description: 'Rebuild confidence in hard seasons',
    category: 'overcoming-adversity',
    type: 'Workbook',
    featured: false,
    downloads: 17200,
    difficulty: 'Intermediate',
    timeToRead: '40 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '54',
    slug: 'adversity-response-framework',
    title: 'Adversity Response Framework',
    description: 'Respond to setbacks effectively',
    category: 'overcoming-adversity',
    type: 'Guide',
    featured: false,
    downloads: 11800,
    difficulty: 'Advanced',
    timeToRead: '35 min',
    targetAudience: 'Senior Leaders',
  },
  {
    id: '55',
    slug: 'bounce-back-plan-template',
    title: 'Bounce-Back Plan Template',
    description: 'Rebuild after disruption',
    category: 'overcoming-adversity',
    type: 'Template',
    featured: false,
    downloads: 14600,
    difficulty: 'Intermediate',
    timeToRead: '30 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '56',
    slug: 'crisis-clarity-checklist',
    title: 'Crisis Clarity Checklist',
    description: 'Stabilize decisions when overwhelmed',
    category: 'overcoming-adversity',
    type: 'Checklist',
    featured: false,
    downloads: 19800,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'All Leaders',
  },
  {
    id: '57',
    slug: 'post-setback-reflection-template',
    title: 'Post-Setback Reflection Template',
    description: 'Extract lessons from setbacks',
    category: 'overcoming-adversity',
    type: 'Template',
    featured: false,
    downloads: 13200,
    difficulty: 'Intermediate',
    timeToRead: '25 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '58',
    slug: 'inner-strength-building-guide',
    title: 'Inner Strength Building Guide',
    description: 'Cultivate emotional endurance',
    category: 'overcoming-adversity',
    type: 'Guide',
    featured: false,
    downloads: 10900,
    difficulty: 'Advanced',
    timeToRead: '40 min',
    targetAudience: 'Senior Professionals',
  },
  {
    id: '59',
    slug: 'healing-through-journaling',
    title: 'Healing Through Journaling',
    description: 'Process stress and regain perspective',
    category: 'overcoming-adversity',
    type: 'PDF',
    featured: false,
    downloads: 22100,
    difficulty: 'Beginner',
    timeToRead: '20 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '60',
    slug: 'recovery-routine-checklist',
    title: 'Recovery Routine Checklist',
    description: 'Daily recovery practices',
    category: 'overcoming-adversity',
    type: 'Checklist',
    featured: false,
    downloads: 15400,
    difficulty: 'Beginner',
    timeToRead: '15 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '61',
    slug: 'grounding-practices-audio',
    title: 'Grounding Practices Audio',
    description: 'Calm your nervous system',
    category: 'overcoming-adversity',
    type: 'Audio',
    featured: false,
    downloads: 18700,
    difficulty: 'Beginner',
    timeToRead: '10 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '62',
    slug: 'resilience-stories-video-series',
    title: 'Resilience Stories Video Series',
    description: 'Real recovery stories and lessons',
    category: 'overcoming-adversity',
    type: 'Video',
    featured: false,
    downloads: 16800,
    difficulty: 'Intermediate',
    timeToRead: '45 min',
    targetAudience: 'All Professionals',
  },
  {
    id: '51',
    slug: 'remote-leadership-audio-coaching',
    title: 'Remote Leadership Audio Coaching',
    description: 'Lead distributed teams effectively',
    category: 'remote-work',
    type: 'Audio',
    featured: false,
    downloads: 9800,
    difficulty: 'Intermediate',
    timeToRead: '25 min',
    targetAudience: 'Remote Leaders',
  },
];

/**
 * Get resource by slug
 */
export function getResourceBySlug(slug: string): Resource | undefined {
  return resources.find((r) => r.slug === slug);
}

/**
 * Get resources by category
 */
export function getResourcesByCategory(category: string): Resource[] {
  if (category === 'all') return resources;
  return resources.filter((r) => r.category === category);
}

/**
 * Get featured resources
 */
export function getFeaturedResources(): Resource[] {
  return resources.filter((r) => r.featured);
}

/**
 * Search resources
 */
export function searchResources(query: string): Resource[] {
  const lowerQuery = query.toLowerCase();
  return resources.filter(
    (r) =>
      r.title.toLowerCase().includes(lowerQuery) ||
      r.description.toLowerCase().includes(lowerQuery) ||
      r.keywords?.some((k) => k.toLowerCase().includes(lowerQuery))
  );
}

/**
 * Get related resources
 */
export function getRelatedResources(resource: Resource, limit = 4): Resource[] {
  return resources
    .filter(
      (r) =>
        r.category === resource.category &&
        r.slug !== resource.slug &&
        !r.featured
    )
    .slice(0, limit);
}
